// <auto-generated />
using System;
using FacturaService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacturaService.Migrations
{
    [DbContext(typeof(FacturaDbContext))]
    partial class FacturaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("FacturaService.Modele.FacturaModel", b =>
                {
                    b.Property<int>("NrFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFactura")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdClient")
                        .HasColumnType("INTEGER");

                    b.HasKey("NrFactura");

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("FacturaService.Modele.ProdusFacturaModel", b =>
                {
                    b.Property<int>("IdProdusFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantitate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProdus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NrFactura")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Pret")
                        .HasColumnType("TEXT");

                    b.HasKey("IdProdusFactura");

                    b.HasIndex("NrFactura");

                    b.ToTable("ProduseFactura");
                });

            modelBuilder.Entity("FacturaService.Modele.ProdusFacturaModel", b =>
                {
                    b.HasOne("FacturaService.Modele.FacturaModel", "Factura")
                        .WithMany("ProduseFactura")
                        .HasForeignKey("NrFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("FacturaService.Modele.FacturaModel", b =>
                {
                    b.Navigation("ProduseFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
