// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Facturi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318064235_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Facturi.ClientModel", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdClient");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("Facturi.FacturaModel", b =>
                {
                    b.Property<int>("NrFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientFacturaIdClient")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFactura")
                        .HasColumnType("TEXT");

                    b.HasKey("NrFactura");

                    b.HasIndex("ClientFacturaIdClient");

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("Facturi.FacturaModel2", b =>
                {
                    b.Property<int>("NrFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientFacturaIdClient")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFactura")
                        .HasColumnType("TEXT");

                    b.HasKey("NrFactura");

                    b.HasIndex("ClientFacturaIdClient");

                    b.ToTable("FacturaModel2");
                });

            modelBuilder.Entity("Facturi.ProdusFacturaModel", b =>
                {
                    b.Property<int>("IdProdusFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantitate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProdus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NrFactura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeProdus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Pret")
                        .HasColumnType("REAL");

                    b.HasKey("IdProdusFactura");

                    b.HasIndex("NrFactura");

                    b.ToTable("ProduseFactura", (string)null);
                });

            modelBuilder.Entity("Facturi.ProdusFacturaModel2", b =>
                {
                    b.Property<int>("IdProdusFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantitate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProdus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NrFactura")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Pret")
                        .HasColumnType("TEXT");

                    b.HasKey("IdProdusFactura");

                    b.HasIndex("IdProdus");

                    b.HasIndex("NrFactura");

                    b.ToTable("ProduseFactura2", (string)null);
                });

            modelBuilder.Entity("Facturi.ProdusModel", b =>
                {
                    b.Property<int>("IdProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeProdus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdProdus");

                    b.ToTable("Produse", (string)null);
                });

            modelBuilder.Entity("Facturi.FacturaModel", b =>
                {
                    b.HasOne("Facturi.ClientModel", "ClientFactura")
                        .WithMany()
                        .HasForeignKey("ClientFacturaIdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientFactura");
                });

            modelBuilder.Entity("Facturi.FacturaModel2", b =>
                {
                    b.HasOne("Facturi.ClientModel", "ClientFactura")
                        .WithMany()
                        .HasForeignKey("ClientFacturaIdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientFactura");
                });

            modelBuilder.Entity("Facturi.ProdusFacturaModel", b =>
                {
                    b.HasOne("Facturi.FacturaModel", "Factura")
                        .WithMany("ProduseFactura")
                        .HasForeignKey("NrFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("Facturi.ProdusFacturaModel2", b =>
                {
                    b.HasOne("Facturi.ProdusModel", "Produs")
                        .WithMany()
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Facturi.FacturaModel2", "Factura")
                        .WithMany("ProduseFactura2")
                        .HasForeignKey("NrFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("Facturi.FacturaModel", b =>
                {
                    b.Navigation("ProduseFactura");
                });

            modelBuilder.Entity("Facturi.FacturaModel2", b =>
                {
                    b.Navigation("ProduseFactura2");
                });
#pragma warning restore 612, 618
        }
    }
}
